site_name: Reaction Kinematics 
site_url: https://det-lab.github.io/reaction-kinematics/

theme:
  name: mkdocs
  color_mode: dark

nav:
  - Getting Started: index.md 
  - Examples: 
    - Computing Kinematic Arrays: comupting-kinematic-arrays.md
    - Accessing Induvidual Values: accessing-induvidual-values.md 
    - Plotting: plotting.md
  - Contribuiting: 
      - Adding to Documentation: contributing.md
      - Suggestions for Code Updates: updatecode.md
  - Api documentation: (https://det-lab.github.io/reaction-kinematics/api/reaction_kinematics.html)